name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install dependencies
        run: |
          poetry run pip install wheel playsound
          poetry install --no-root
          poetry show

      - name: Build
        run: |
          poetry run pyinstaller --onefile src/can_id_scanner/scanner.py
          poetry run pyinstaller --onefile src/can_id_scanner/list_devices.py
          ls -l dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}
          path: dist/*
